# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_e = QtWidgets.QFrame(self.centralwidget)
        self.frame_e.setObjectName("frame_e")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_e)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_e_3 = QtWidgets.QLabel(self.frame_e)
        self.label_e_3.setObjectName("label_e_3")
        self.gridLayout_2.addWidget(self.label_e_3, 3, 0, 1, 1)
        self.lineEditCityIDDesc = QtWidgets.QLineEdit(self.frame_e)
        self.lineEditCityIDDesc.setObjectName("lineEditCityIDDesc")
        self.gridLayout_2.addWidget(self.lineEditCityIDDesc, 5, 4, 1, 2)
        self.lineEditTimezone = QtWidgets.QLineEdit(self.frame_e)
        self.lineEditTimezone.setObjectName("lineEditTimezone")
        self.gridLayout_2.addWidget(self.lineEditTimezone, 4, 1, 1, 1)
        self.dateEditTo = QtWidgets.QDateEdit(self.frame_e)
        self.dateEditTo.setCalendarPopup(True)
        self.dateEditTo.setObjectName("dateEditTo")
        self.gridLayout_2.addWidget(self.dateEditTo, 3, 4, 1, 2)
        self.line_e_2 = QtWidgets.QFrame(self.frame_e)
        self.line_e_2.setLineWidth(0)
        self.line_e_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_e_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_e_2.setObjectName("line_e_2")
        self.gridLayout_2.addWidget(self.line_e_2, 3, 2, 3, 1)
        self.label_e_8 = QtWidgets.QLabel(self.frame_e)
        self.label_e_8.setObjectName("label_e_8")
        self.gridLayout_2.addWidget(self.label_e_8, 5, 3, 1, 1)
        self.label_e_4 = QtWidgets.QLabel(self.frame_e)
        self.label_e_4.setObjectName("label_e_4")
        self.gridLayout_2.addWidget(self.label_e_4, 3, 3, 1, 1)
        self.label_e_6 = QtWidgets.QLabel(self.frame_e)
        self.label_e_6.setObjectName("label_e_6")
        self.gridLayout_2.addWidget(self.label_e_6, 4, 3, 1, 1)
        self.label_e_5 = QtWidgets.QLabel(self.frame_e)
        self.label_e_5.setObjectName("label_e_5")
        self.gridLayout_2.addWidget(self.label_e_5, 4, 0, 1, 1)
        self.label_e_7 = QtWidgets.QLabel(self.frame_e)
        self.label_e_7.setObjectName("label_e_7")
        self.gridLayout_2.addWidget(self.label_e_7, 5, 0, 1, 1)
        self.label_e = QtWidgets.QLabel(self.frame_e)
        self.label_e.setObjectName("label_e")
        self.gridLayout_2.addWidget(self.label_e, 0, 0, 1, 1)
        self.lineEditCityID = QtWidgets.QLineEdit(self.frame_e)
        self.lineEditCityID.setObjectName("lineEditCityID")
        self.gridLayout_2.addWidget(self.lineEditCityID, 5, 1, 1, 1)
        self.line_e = QtWidgets.QFrame(self.frame_e)
        self.line_e.setLineWidth(0)
        self.line_e.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_e.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_e.setObjectName("line_e")
        self.gridLayout_2.addWidget(self.line_e, 2, 0, 1, 6)
        self.comboBoxCityIDLayer = QtWidgets.QComboBox(self.frame_e)
        self.comboBoxCityIDLayer.setObjectName("comboBoxCityIDLayer")
        self.gridLayout_2.addWidget(self.comboBoxCityIDLayer, 4, 4, 1, 2)
        self.dateEditFrom = QtWidgets.QDateEdit(self.frame_e)
        self.dateEditFrom.setCalendarPopup(True)
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.gridLayout_2.addWidget(self.dateEditFrom, 3, 1, 1, 1)
        self.label_e_2 = QtWidgets.QLabel(self.frame_e)
        self.label_e_2.setObjectName("label_e_2")
        self.gridLayout_2.addWidget(self.label_e_2, 1, 0, 1, 1)
        self.lineEditBrowse = QtWidgets.QLineEdit(self.frame_e)
        self.lineEditBrowse.setReadOnly(True)
        self.lineEditBrowse.setPlaceholderText("Click to browse ..")
        self.lineEditBrowse.setObjectName("lineEditBrowse")
        self.gridLayout_2.addWidget(self.lineEditBrowse, 1, 1, 1, 5)
        self.comboBoxThematic = QtWidgets.QComboBox(self.frame_e)
        self.comboBoxThematic.setObjectName("comboBoxThematic")
        self.gridLayout_2.addWidget(self.comboBoxThematic, 0, 1, 1, 5)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 2)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout.addWidget(self.frame_e, 2, 0, 1, 2)
        self.frame_e_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_e_2.setObjectName("frame_e_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_e_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonReset = QtWidgets.QPushButton(self.frame_e_2)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridLayout_3.addWidget(self.pushButtonReset, 1, 1, 1, 1)
        self.pushButtonCreate = QtWidgets.QPushButton(self.frame_e_2)
        self.pushButtonCreate.setDefault(True)
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.gridLayout_3.addWidget(self.pushButtonCreate, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_e_2)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.frame_e_2, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxThematic, self.lineEditBrowse)
        MainWindow.setTabOrder(self.lineEditBrowse, self.dateEditFrom)
        MainWindow.setTabOrder(self.dateEditFrom, self.dateEditTo)
        MainWindow.setTabOrder(self.dateEditTo, self.lineEditTimezone)
        MainWindow.setTabOrder(self.lineEditTimezone, self.comboBoxCityIDLayer)
        MainWindow.setTabOrder(self.comboBoxCityIDLayer, self.lineEditCityID)
        MainWindow.setTabOrder(self.lineEditCityID, self.lineEditCityIDDesc)
        MainWindow.setTabOrder(self.lineEditCityIDDesc, self.tableWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_e_3.setText(_translate("MainWindow", "From Date"))
        self.dateEditTo.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.label_e_8.setText(_translate("MainWindow", "CityID Desc"))
        self.label_e_4.setText(_translate("MainWindow", "To Date"))
        self.label_e_6.setText(_translate("MainWindow", "CityID Layer"))
        self.label_e_5.setText(_translate("MainWindow", "Timezone"))
        self.label_e_7.setText(_translate("MainWindow", "CityID"))
        self.label_e.setText(_translate("MainWindow", "Thematic"))
        self.dateEditFrom.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.label_e_2.setText(_translate("MainWindow", "Template"))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset"))
        self.pushButtonCreate.setText(_translate("MainWindow", "Create Script"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Parameter"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "mcc"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "mcc desc"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "mnc"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "321"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "mnc desc"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "daytime"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "456"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "daytime description"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

